package templates

import (
	"io"
	"text/template"
)

const proxySaltBrokerTemplate = `# uyuni-proxy-salt-broker.service, generated by uyuniadm
# Use an uyuni-proxy-salt-broker.service.d/local.conf file to override

[Unit]
Description=Uyuni proxy Salt broker container service
Wants=network.target
After=network-online.target
BindsTo=uyuni-proxy-pod.service
After=uyuni-proxy-pod.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
EnvironmentFile={{ .ProxySystemdConfigPath }}
EnvironmentFile={{ .ProxyConfigFolder}}
EnvironmentFile=-{{ .ProxySaltBrokerConfigPath}}
Restart=on-failure
ExecStartPre=/bin/rm -f %t/uyuni-proxy-salt-broker.pid %t/uyuni-proxy-salt-broker.ctr-id

Environment=UYUNI_IMAGE={{ .Image }}
ExecStart=/usr/bin/podman run \
    --conmon-pidfile %t/{{ .NamePrefix }}-proxy-salt-broker.pid \
    --cidfile %t/{{ .NamePrefix }}-proxy-salt-broker.ctr-id \
    --cgroups=no-conmon \
    --pod-id-file %t/{{ .NamePrefix }}-proxy-pod.pod-id -d \
    --replace -dt \
	  {{- range $name, $path := .Volumes }}
	  -v {{ $name }}:{{ $path }} \
	  {{- end }}
    --name {{ .NamePrefix }}-proxy-salt-broker ${UYUNI_IMAGE}

ExecStop=/usr/bin/podman stop --ignore --cidfile %t/{{ .NamePrefix }}-proxy-salt-broker.ctr-id -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/{{ .NamePrefix }}-proxy-salt-broker.ctr-id
PIDFile=%t/{{ .NamePrefix }}-proxy-salt-broker.pid
TimeoutStopSec=60
Type=forking

[Install]
WantedBy=multi-user.target default.target
`

type PodmanProxySaltBrokerTemplateData struct {
	Volumes                   map[string]string
	ProxySystemdConfigPath    string
	ProxyConfigFolder         string
	ProxySaltBrokerConfigPath string
	NamePrefix                string
}

func (data PodmanProxySaltBrokerTemplateData) Render(wr io.Writer) error {
	t := template.Must(template.New("service").Parse(proxySaltBrokerTemplate))
	return t.Execute(wr, data)
}
